#!/usr/bin/python3

import pytz
from datetime import datetime, time
import sys

def show_current_and_market_times(timezone):
    
    tz = pytz.timezone(timezone)

    

    #utc time
    now_utc = datetime.now(pytz.utc)

    #time import
    now_tz = now_utc.astimezone(tz)
    tokyo_tz = pytz.timezone('Asia/Tokyo')
    now_tokyo = now_utc.astimezone(tokyo_tz)
    ny_tz = pytz.timezone('America/New_York')
    now_ny = now_utc.astimezone(ny_tz)

    #tokyo opentime - closetime
    tokyo_open = time(9, 0, 0)
    tokyo_close = time(15, 0, 0)

    #ny
    ny_open = time(9, 30, 0)
    ny_close = time(16, 0, 0)
    
    #now time
    print(f": {now_utc.strftime('%Y-%m-%d %H:%M:%S')}")
    print(f": {now_tokyo.strftime('%Y-%m-%d %H:%M:%S')}")
    print(f": {now_ny.strftime('%Y-%m-%d %H:%M:%S')}")
    print()

    #open - close
    print(f": {tokyo_open.strftime('%H:%M:%S')} - {tokyo_close.strftime('%H:%M:%S')} (JST)")
    print(f": {ny_open.strftime('%H:%M:%S')} - {ny_close.strftime('%H:%M:%S:')}")
    print()

if __name__ == "__main__":
    timezone = sys.stdin.read().strip()
    show_current_and_market_times(timezone)

